swagger: '2.0'

schemes:
  - http

basePath: /accounting/v1

host: localhost

info:
  description: 'The invoice service enables client upload, view, ammend and cancel invoices'
  version: v1
  title: Invoice API

tags:
  - name: Invoice Upload
    description: ' '
  - name: Invoice List
    description: ' '
  - name: Invoice Amendment
    description: ' '
  - name: Invoice Cancellation
    description: ' '


paths:
  /invoices:
    get:
      tags:
        - Invoice List
      responses:
        '200':
          description: A list of invoices
          schema:
            $ref: '#/definitions/invoices'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
      parameters:
        - required: true
          description: Filter invoices by start date range
          type: string
          in: query
          name: fromDate
        - description: Filter invoices by end date range
          type: string
          in: query
          name: toDate
        - description: Filter invoices by type. Either SALE or PURCHASE type
          type: string
          in: query
          name: invoiceType
          required: true
    post:
      tags:
        - Invoice Upload
      consumes: 
       - multipart/form-data
      parameters: 
       - name: X-koweg-header-requestId
         in: header
         type: string
         required: false
       - name: invoiceData
         in: formData
         type: file
         required: false
       - name: invoiceType
         in: formData
         type: string
         enum: 
          - SALES
          - PURCHASE
         required: true  
      responses:
        '200':
          description: Invoice successfully created
          headers:
            Location:
              type: string
              format: url
          schema:
            $ref: '#/definitions/invoice'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      tags:
        - Invoice Amendment
      responses:
        '204':
          description: Invoice successfully amended - no content
        '401':
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
      parameters:
        - schema:
            $ref: '#/definitions/partialinvoice'
          in: body
          name: body
  '/invoices/{invoiceId}':
    get:
      tags:
        - Invoice List
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/invoice'
        '401':
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
      parameters:
       - type: string
         in: path
         name: invoiceId
         required: true
    delete:
      tags:
        - Invoice Cancellation
      responses:
        '204':
          description: Invoice successfully deleted - no content
        '401':
          description: ''
          schema:
            $ref: '#/definitions/ErrorResponse'
      parameters:
       - type: string
         in: path
         name: invoiceId
         required: true



definitions:
  AmountType:
    type: object
    properties:
      amount:
        format: double
        type: number
      curr:
        type: string
        minLength: 3
        maxLength: 3
  invoice:
    description: An invoice presentation
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      amount:
        $ref: '#/definitions/AmountType'
      invoiceType:
        enum:
          - PURCHASE
          - SALE
        type: string
      country:
        type: string
    required:
      - id
      - date
      - amount
      - country
      - invoiceType
  invoices:
    type: array
    minItems: 1
    maxItems: 100
    items:
      $ref: '#/definitions/invoice'
  partialinvoice:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      country:
        type: string
      invoiceType:
        enum:
          - PURCHASE
          - SALE
        type: string
    required:
      - id
  ErrorResponse:
    description: Error response message
    properties:
      code:
        minLength: 1
        type: string
      correlationId:
        minLength: 1
        type: string
      description:
        minLength: 1
        type: string
    required:
      - correlationId
      - code
      - description
    type: object
